pipeline {
    agent any

    tools {
        maven '3.9.2'
    }
    stages {
        stage("Tools initialization") {
            steps {
 
                sh "mvn --version"
                sh "java -version"
            }
        }

    environment {
        EC2_USER = 'ubuntu'
        EC2_HOST = 'your-ec2-public-ip'
        SSH_KEY = '/path/to/your-key.pem'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/mohanakrishna732/java-maven.git'
            }
        }

        stage('Compile') {
            steps {
                sh 'mvn compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'

         stage('Artifacts') {
            steps {
                sh 'mvn clean package'
            }       
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Deliver') {
            steps {
                sh 'scp -i $SSH_KEY target/*.jar $EC2_USER@$EC2_HOST:/home/ubuntu/app.jar'
                sh 'ssh -i $SSH_KEY $EC2_USER@$EC2_HOST "nohup java -jar /home/ubuntu/app.jar > /home/ubuntu/app.log 2>&1 &"'
            }
        }
    }
}
