pipeline {
    agent any

    tools {
        maven '3.9.2'
    }

    environment {
        EC2_USER = 'ubuntu'
        EC2_HOST = '35.181.167.228'
        SSH_KEY = '/home/ubuntu/server.pem'
    }

    stages {
        stage("Tools initialization") {
            steps {
                sh "mvn --version"
                sh "java -version"
            }
        }

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/mohanakrishna732/java-maven.git'
            }
        }

        stage('Compile') {
            steps {
                sh 'mvn compile'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

        stage('Artifacts') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Deliver') {
            steps {
                sh 'scp -i $SSH_KEY /var/lib/jenkins/workspace/new-job1/target/*.jar $EC2_USER@$EC2_HOST:/opt/tomcat/webapps/manager/app.jar'
                sh 'ssh -i $SSH_KEY $EC2_USER@$EC2_HOST "nohup java -jar /opt/tomcat/webapps/manager/app.jar > /home/ubuntu/app.log 2>&1 &"'
            }
        }
    }
}
